Repository Exiled-Official/EXILED, pull requests merged in 2024-07, with the labels that each got.

#74 Automate release process
  .github/workflows/release.yml
Labels: enhancement

#66 Add Nearest rooms
  EXILED/Exiled.API/Features/Room.cs
  EXILED/Exiled.Events/Patches/Generic/DoorList.cs
  EXILED/Exiled.Events/Patches/Generic/RoomList.cs
Labels: enhancement

#68 Add healing and healed events
  EXILED/Exiled.Events/EventArgs/Player/HealedEventArgs.cs
  EXILED/Exiled.Events/EventArgs/Player/HealingEventArgs.cs
  EXILED/Exiled.Events/Handlers/Player.cs
  EXILED/Exiled.Events/Patches/Events/Player/Healing.cs
Labels: enhancement

#71 Add PlayGunSound
  EXILED/Exiled.API/Features/Map.cs
Labels: enhancement

#70 Add Scp244Spawning event
  EXILED/Exiled.Events/EventArgs/Map/Scp244SpawningEventArgs.cs
  EXILED/Exiled.Events/Handlers/Map.cs
  EXILED/Exiled.Events/Patches/Events/Map/Scp244Spawning.cs
Labels: enhancement

#69 Fix SetRoomColorForTargetOnly
  EXILED/Exiled.API/Extensions/MirrorExtensions.cs
Labels: bug

#76 CreditTags Reimplementation.
  EXILED/Exiled.CreditTags/Commands/ShowCreditTag.cs
  EXILED/Exiled.CreditTags/CreditTags.cs
  EXILED/Exiled.CreditTags/Enums/InfoSide.cs
  EXILED/Exiled.CreditTags/Enums/RankType.cs
  EXILED/Exiled.CreditTags/Events/CreditsHandler.cs
  EXILED/Exiled.CreditTags/Exiled.CreditTags.csproj
  EXILED/Exiled.CreditTags/Features/DatabaseHandler.cs
  EXILED/Exiled.CreditTags/Features/TagItem.cs
  EXILED/Exiled.CreditTags/Features/ThreadSafeRequest.cs
Labels: tested

#72 Fix particle disruptor ammo
  EXILED/Exiled.API/Features/Pickups/FirearmPickup.cs
Labels: base-game-bug, regarding-api

#103 fIx StranglingEventCrash
  EXILED/Exiled.Events/EventArgs/Scp3114/StranglingEventArgs.cs
  EXILED/Exiled.Events/Patches/Events/Scp3114/Strangling.cs
Labels: bug, tested, regarding-events, regarding-transpiler

#110 Things primitive😨😍🤓😈🙂☕☕
  EXILED/Exiled.API/Features/Toys/AdminToy.cs
  EXILED/Exiled.API/Features/Toys/Light.cs
  EXILED/Exiled.API/Features/Toys/Primitive.cs
  EXILED/Exiled.API/Features/Toys/ShootingTargetToy.cs
Labels: bug, regarding-api

#108 Fix `SpawningRagdoll::IsAllowed = false`
  EXILED/Exiled.Events/Patches/Events/Player/SpawningRagdoll.cs
Labels: bug, tested, regarding-transpiler

#109 `ChangingRadioPresetEventArgs::Radio` property
  EXILED/Exiled.Events/EventArgs/Player/ChangingRadioPresetEventArgs.cs
  EXILED/Exiled.Events/Patches/Events/Player/ChangingRadioPreset.cs
Labels: tested, regarding-events, regarding-transpiler

#75 Add `InstantKill` property
  EXILED/Exiled.Events/EventArgs/Player/HurtingEventArgs.cs
Labels: tested, regarding-events
